<?php


namespace GD\Tests;

class WriteFileBrowserTest extends TestCase
{

    public function setUp()
    {
        parent::setUp();

        $this->default_test_type = 'browser';

        $this->setupFolderAndFile();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->cleanUpFile();
    }

    public function testShouldMakeFileWithCorrectName()
    {
        $path = $this->gd->setContext('ui')
                ->getDestinationFolderRoot() . '/tests/Browser/TestNamingTest.php';
        \PHPUnit_Framework_Assert::assertFileNotExists($path);

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->setContext('browser')
            ->initializeFeature();


        \PHPUnit_Framework_Assert::assertEquals(
            getcwd() . '/tests/Browser',
            $this->gd->getDestinationFolderRoot()
        );

        \PHPUnit_Framework_Assert::assertFileExists(
            $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php'
        );
    }

    public function testMakeFileForBrowser()
    {
        $path = $this->gd->setContext('ui')
                ->getDestinationFolderRoot() . '/tests/Browser/TestNamingTest.php';
        \PHPUnit_Framework_Assert::assertFileNotExists($path);

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->setContext('browser')
            ->initializeFeature();

        $fixture_path = __DIR__ . '/fixtures/TestNamingTest.phpBROWSER_EXAMPLE';

        $results_path = $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php';

        \PHPUnit_Framework_Assert::assertFileEquals($results_path, $fixture_path);
    }
}
