<?php


namespace GD\Tests;

class WriteFileBrowserTest extends TestCase
{

    public function setUp()
    {
        parent::setUp();
        $this->instantiateGD();

        $this->setupFolderAndFile();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->cleanUpFile();
    }

    public function testShouldMakeFileWithCorrectName()
    {
        $this->markTestSkipped("taking break");
        $path = $this->gd->setContext('ui')
                ->getDestinationFolderRoot() . '/tests/Browser/TestNamingTest.php';
        \PHPUnit_Framework_Assert::assertFileNotExists($path);

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->setContext('browser')
            ->initializeFeature();


        //dd($this->gd->setContext('browser')->getDestinationFolderRoot());
        \PHPUnit_Framework_Assert::assertEquals(
            getcwd() . '/tests/Browser',
            $this->gd->setContext('ui')->getDestinationFolderRoot()
        );

        \PHPUnit_Framework_Assert::assertFileExists(
            $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php'
        );
    }
}
