<?php


namespace GD\Tests;

class WriteFileTest extends TestCase
{


    public function setUp()
    {
        parent::setUp();
        $this->instantiateGD();

        $this->setupFolderAndFile();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->cleanUpFile();
    }

    public function testShouldMakeFileWithCorrectName()
    {
        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->initializeFeature();


        \PHPUnit_Framework_Assert::assertEquals(getcwd() . '/tests/',
            $this->gd->getDestinationFolderRoot());

        \PHPUnit_Framework_Assert::assertFileExists($this->gd->getDestinationFolderRoot() . '/tests/TestNamingTest.php');
        //dd($this->gd->getDuskClassAndMethods());
    }

    public function testFileShouldMatchExpected()
    {
    }
}
