<?php


namespace GD\Tests;

use GD\Exceptions\TestFileExists;

class WriteFileTest extends TestCase
{

    public function setUp()
    {
        parent::setUp();
        $this->setupFolderAndFile();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $this->cleanUpFile();
    }

    public function testShouldMakeFileWithCorrectName()
    {
        $path = $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php';
        \PHPUnit_Framework_Assert::assertFileNotExists($path);

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->initializeFeature();


        \PHPUnit_Framework_Assert::assertEquals(
            getcwd() . '/tests/Feature',
            $this->gd->getDestinationFolderRoot()
        );

        \PHPUnit_Framework_Assert::assertFileExists(
            $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php'
        );
    }

    public function testFileShouldMatchExpected()
    {
        $path = $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php';
        \PHPUnit_Framework_Assert::assertFileNotExists($path);

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->initializeFeature();

        $contains = <<<HEARDOC
<?php

namespace Tests\Unit;

use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class {$this->gd->getDuskTestName()} extends TestCase
{
HEARDOC;

        $content = $this->gd->getWriteUnitTest()->getDuskClassAndMethodsString();
        \PHPUnit_Framework_Assert::assertContains($contains, $content);

        \PHPUnit_Framework_Assert::assertContains("function testEditProfile()", $content);

        \PHPUnit_Framework_Assert::assertContains("protected function givenIHaveAProfileCreated() {", $content);
        \PHPUnit_Framework_Assert::assertContains("\$this->givenIHaveAProfileCreated", $content);

        /**
         * Then do the file
         */
        $fixture = file_get_contents(__DIR__ . '/fixtures/TestNamingTest.phpTEMPLATE');
        $content = file_get_contents($this->gd->getDestinationFolderRoot() . '/TestNamingTest.php');
        //$this->file->put(__DIR__ . '/fixtures/TestNamingTest.phpTEMPLATE', $content);

        \PHPUnit_Framework_Assert::assertEquals($fixture, $content);
    }

    public function testPreventDuplicateMethods()
    {
        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->initializeFeature();

        $content = file_get_contents($this->gd->getDestinationFolderRoot() . '/TestNamingTest.php');

        $find = substr_count($content, "protected function andTheLastName()");

        \PHPUnit_Framework_Assert::assertEquals(1, $find);
    }

    /**
     * @expectedException \GD\Exceptions\TestFileExists
     */
    public function testPreventOverwrite()
    {
        $path = $this->gd->getDestinationFolderRoot() . '/TestNamingTest.php';
        if (!$this->file->exists($path)) {
            if (!$this->file->exists($this->gd->getDestinationFolderRoot())) {
                $this->file->makeDirectory($this->gd->getDestinationFolderRoot(), 0777, true);
            }

            $this->file->put($path, "Foo");
        }

        $path = 'tests/features/test_naming.feature';
        $this->gd->setPathToFeature($path)
            ->initializeFeature();
    }
}
